apiVersion: v1
kind: Namespace
metadata:
  name: shopmicro
  labels:
    name: shopmicro
    app.kubernetes.io/name: shopmicro
    app.kubernetes.io/instance: production
---
apiVersion: v1
kind: LimitRange
metadata:
  name: shopmicro-limits
  namespace: shopmicro
spec:
  limits:
  - type: Container
    default:
      memory: "512Mi"
      cpu: "500m"
    defaultRequest:
      memory: "256Mi"
      cpu: "100m"
    max:
      memory: "1Gi"
      cpu: "1000m"
    min:
      memory: "128Mi"
      cpu: "50m"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: shopmicro-quota
  namespace: shopmicro
spec:
  hard:
    requests.cpu: "2000m"
    requests.memory: 4Gi
    limits.cpu: "4000m"
    limits.memory: 8Gi
    count/persistentvolumeclaims: "4"
    count/services: "10"
    count/secrets: "10"
    count/configmaps: "10"